# fly.toml file generated for zipfs on 2022-11-20T01:10:43Z

app = "zipfs"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  DATA = "/data"
  IPFS_LOGGING = ""
  IPFS_PATH = "/data/ipfs"
  IPFS_PROFILE = "server"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/data/ipfs"
  source = "ipfs_data"

[[services]]
  internal_port = 4001
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 1000
    type = "connections"

  [[services.ports]]
    port = 4001

[[services]]
  internal_port = 4001
  protocol = "udp"
  [services.concurrency]
    hard_limit = 1000
    type = "connections"

  [[services.ports]]
    port = 4001
