apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zebu
  name: zebu
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zebu
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zebu
    spec:
      containers:
      - image: paulgmiller/zebu:dfce1d
        name: zebu
        resources: 
          requests:
            cpu: 50m
            memory: 100Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: "IPFS_SERVER"
          value : "zipfs:5001"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
     

      
