apiVersion: v1
kind: Service
metadata:
  labels:
    app: northbriton
  name: northbriton  
spec:
  clusterIP: 10.0.126.128
  clusterIPs:
  - 10.0.126.128
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-8000
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: northbriton
  sessionAffinity: None
  type: ClusterIP
