apiVersion: batch/v1
kind: CronJob
metadata:
  name: importer
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      name: importer
    spec:
      ttlSecondsAfterFinished: 120000
      template:
        spec:
          containers:
          - image: paulgmiller/zebu:0d1d03f
            imagePullPolicy: IfNotPresent
            args: ["-import", "/opml/paul.opml"]
            name: importer
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            env:
            - name: "IPFS_SERVER"
              value : "/dns4/zipfs/tcp/5001/"
            volumeMounts:
            - name: opml
              mountPath: /opml/
              readOnly: true
            - name: importkeys
              mountPath: /import_keys/
              readOnly: false #new secrets get written in?
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - name: opml
            configMap:
              name: opml
          - name: importkeys
            secret:
              secretName: importkeys
  schedule: '* */4 * * *'
  successfulJobsHistoryLimit: 3
  suspend: false

