apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: zebu
  name: zebu
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  loadBalancerIP: 20.150.158.188
  clusterIP: 10.0.193.46
  clusterIPs:
  - 10.0.193.46
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 80-9000
    nodePort: 32709
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    app: zebu
  sessionAffinity: None
  type: LoadBalancer
