apiVersion: v1
kind: Service
metadata:
  labels:
    app: swarm
  name: swarm
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Local
  internalTrafficPolicy: Local
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: swarm-tcp
    nodePort: 31879
    port: 4001
    protocol: TCP
    targetPort: 4001
  - name: swarm-udp
    nodePort: 32738
    port: 4001
    protocol: UDP
    targetPort: 4001
  selector:
    app: zipfs
  sessionAffinity: None
  type: LoadBalancer
